# Generated by Django 4.1.1 on 2022-10-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=1000)),
                ('short_url', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
