# Generated by Django 4.1.1 on 2022-10-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='long_url',
            new_name='url',
        ),
    ]
